### ISSUE TITLE
请问如何设置时区？

### ISSUE THREAD

**Issue by Shimada666** [sakarie9/Go-CQHTTP-Docker#1]
我使用了以下办法，但是没用，时区还是 utc
```yaml
version: "3"

services:
  client:
    image: xzsk2/gocqhttp-docker:latest
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./client:/data:delegated
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on:
      - bot

  bot:
    build: ./bot
    expose:
      - "9080"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

networks:
  default:
    name: workspace-default

```

进入容器查看 /etc/timezone，确实为 Asia/Shanghai
